### DISCUSSION TITLE
Is it possible to set the AllowKey parameter?

### DISCUSSION THREAD

**Discussion by tgglatitude** [zabbix-community/helm-zabbix#175] [Q&A] [answered]
Hello everyone,

Is there any way for me to add `AllowKey: "system.run[*]` to my chart's deployment? 

I'm deploying the `zabbix-agent2` and already tried:
```
zabbixAgent:
   config:
     AllowKey: "system.run[*]"
```
```
extraEnv:
  - name: ZBX_ENABLEREMOTECOMMANDS
    value: "1"
  - name: ZBX_ALLOWKEY
    value: "system.run[*]"
```
```
zabbixAgent:
  ZBX_ENABLEREMOTECOMMANDS: 1
  ZBX_ALLOWKEY: "system.run[*]"
  ZBX_LOGREMOTECOMMANDS: 1
```

But it never works, I always get the error `Unknown metric: system.run` on my Zabbix Server's UI and can't see the parameter being set. Is there any workaround for this?

**Comment by aeciopires** [comment, marked as answer]
Hello @tgglatitude!

According to the Docker Hub for zabbix-agent2 (https://hub.docker.com/r/zabbix/zabbix-agent2), there is a list of extra environment variables!

That means you can do something like:

My example:

```yaml
zabbixAgent:
  enabled: true
  # Other hidden parameters
  # [...]
  extraEnv:
    - name: ZBX_ALLOWKEY
      value: "system.run[*]"
```

This configuration will create the line ``AllowKey=system.run[*]`` inside the ``/etc/zabbix/zabbix_agent2_item_keys.conf`` file in the zabbix-agent container.

Change the values ​​according to your needs.

Can you test this?
