### DISCUSSION TITLE
Persistent volume inside server pod

### DISCUSSION THREAD

**Discussion by atxbyea** [zabbix-community/helm-zabbix#176] [Q&A] [answered]
I cannot seem to find any examples on how to do persistence in the server pod, just the agent pods.

The usecase is I have scripts that I need to run inside the server container (email etc) and these need to be persistent.
To be able to do snmptrap doesn't that also require local file edits ? I might have misunderstood that part.

Hope it is just me that is an idiot :-)

**Comment by aeciopires** [comment, marked as answer]
Hello @atxbyea!

For Zabbix Server and other components is the same way to add persistent config files and scripts...

1) You should create a configMap object in Kubernetes cluster containing the file/script following the official doc: 

- https://kubernetes.io/docs/concepts/configuration/configmap/
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

2) You should refer in the ``values.yaml`` custom file the configMap name and the target path in the Zabbix-Server pod like this example:

```yaml
zabbixServer:
  enabled: true
  # hidden other parameters
  extraVolumes:
  - name: file1-example
    configMap:
      name: configmap-file1
  - name: file2-example
    configMap:
      name: configmap-file2
  extraVolumeMounts:
  - name: file1-example
    mountPath: /etc/zabbix/file1.txt
  - name: file2-example
    mountPath: /opt/file2.txt

```

Have a nice day
