### DISCUSSION TITLE
Probes for zabbixServer component

### DISCUSSION THREAD

**Discussion by freakytoad1** [zabbix-community/helm-zabbix#185] [Q&A] [answered]
The default values.yaml does not include any liveness, readiness, or startup probes for the zabbix server component. I added a few so k8s knows if the component is healthy or not.

```yaml
startupProbe:
  tcpSocket:
    port: 10051
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 12
  successThreshold: 1
```
and similar for the other probes.

I'm running zabbix in HA and the active one is responding to the probes and saying it is up but the standby one is seemingly not responding to the probes so k8s keeps killing it and restarting it.

Is it recommended to use probes in this set up? Does zabbix itself handle the HA health and failover? Do I need different probe settings?
