### DISCUSSION TITLE
How do you expose services to outside world?

### DISCUSSION THREAD

**Discussion by BGmot** [zabbix-community/helm-zabbix#27] [General]
Hello,
I see default type for all services in this chart is `ClusterIP`. I see the need to expose at least Zabbix server and Zabbix web to the world outside k8s cluster. How do you do that in real life (not lab)?
I am asking because my provider suggests using `Loadbalancer` type but every loadbalancer instance costs money. What if I want to run several Zabbix server instances? Plus terminating TLS traffic for web component - where? Maybe it is more reasonable deploy one (redundant) proxy (HA-poxy?) and based on FQDN route traffic to different Zabbix web instances, based on TCP ports route traffic to different Zabbix server?
Thanks.

**Comment by aeciopires** [comment]
Hi @BGmot!

Great and difficult question!!!

We set ClusterIP as the default for make it easy install Zabbix in any kind of environment or Kubernetes cluster without exposing unnecessary application, even if you are a begginer in the Kubernetes world.

According this [section](https://github.com/zabbix-community/helm-zabbix/tree/master/charts/zabbix#configure-the-way-how-to-expose-zabbix-service) of helm chart README.md, if you need to expose some service you can use:

- **Ingress**: The ingress controller must be installed in the Kubernetes cluster. Examples: [nginx-ingress](https://kubernetes.github.io/ingress-nginx/), [traefik](https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/)
- **IngressRoute**: The custom resource definition if you use the [Traefik](https://traefik.io/traefik/) ingress controller.
- **Route**: The ingress controller used by Red Hat Openshift, based on HAProxy
- **ClusterIP**: Exposes the service on a cluster-internal IP. Choosing this value makes the service only reachable from within the cluster.
- **NodePort**: Exposes the service on each Node’s IP at a static port (the NodePort). You’ll be able to contact the NodePort service, from outside the cluster, by requesting NodeIP:NodePort.
- **LoadBalancer**: Exposes the service externally using a cloud provider’s load balancer. 

*LoadBalancer services will create an internal Kubernetes Service that is connected to a Load Balancer provided by your cloud provider (AWS, GCP, or Azure). This will create a publicly addressable set of IP addresses and a DNS name that can be used to access your cluster from an external source.* [[1](https://www.bluematador.com/blog/an-introduction-to-kubernetes-services)]

For on-premisse environment you can use [MetalLB](https://metallb.universe.tf/) to creation of LoadBalancer without expend money.

Another option is to use the ingress. With ingress you have a behavior like VirtualHost of Apache or Nginx (do you remember?). You create a unique Loadbalancer for ingress controller and create many routes (like redirects) according DNS name in [Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) header of HTTP request to redirect to service name in Kubernetes cluster. This way you save money as you don't have to create a LoadBalancer for each service you want to expose.

In my case, I use [EKS](https://aws.amazon.com/eks/) with ALB (Application Loadbalancer) [[2](https://aws.amazon.com/elasticloadbalancing/)] [[3](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/)] and [GKE](https://cloud.google.com/kubernetes-engine) with [Network Loadbalancer](https://cloud.google.com/kubernetes-engine/docs/how-to/exposing-apps). Each cloud provider has differente features for Loadbalancer configured by annotations like [[4](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/)] or [[5](https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer-parameters)].

All this configurations can be defined in helm values. See my example (this is a configuration for exposing a fake application deployed in AWS-EKS without using ingress-controller (like nginx-ingress or traefik). Change according your need):

```yaml
service:
  type: NodePort  #This type is used together with the annotations seted in ingress to create a LoadBalancer ALB in AWS (layer 7 of OSI model).
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: 
    # References:
    # https://docs.aws.amazon.com/pt_br/prescriptive-guidance/latest/patterns/deploy-a-grpc-based-application-on-an-amazon-eks-cluster-and-access-it-with-an-application-load-balancer.html
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/
    # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2346
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:CHANGE_AWS_REGION:CHANGE_AWS_ACCOUNT:certificate/CHANGE_ID_AWS_CERTIFICATE
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    alb.ingress.kubernetes.io/tags: Scost=my-fake-application, Environment=testing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/security-groups: CHANGE_AWS_SECURITY_GROUP_ID
  hosts:
    - host: my-fake-aplication.aeciopires.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
```

After this, a DNS name of loadbalancer will created by AWS and I will need to create a CNAME record in my DNS domain to ``my-fake-aplication.aeciopires.com`` redirect the DNS name of loadbalancer.

Some documentation about services in Kubernetes:

-  https://medium.com/devops-mojo/kubernetes-service-types-overview-introduction-to-k8s-service-types-what-are-types-of-kubernetes-services-ea6db72c3f8c
- https://dev.to/pavanbelagatti/kubernetes-service-types-explained-207g
- https://www.ibm.com/docs/en/cloud-private/3.2.0?topic=networking-kubernetes-service-types
- https://kubernetes.io/docs/concepts/services-networking/service/
- https://komodor.com/learn/kubernetes-service-examples-basic-usage-and-troubleshooting/
- https://matthewpalmer.net/kubernetes-app-developer/articles/service-kubernetes-example-tutorial.html
- https://www.bluematador.com/blog/an-introduction-to-kubernetes-services
- https://www.cortex.io/post/understanding-kubernetes-services-ingress-networking
- https://collabnix.github.io/kubelabs/Services101/
- https://kubernetes.io/docs/concepts/services-networking/ingress/

**Reply by BGmot** [reply]
Thanks @aeciopires!
A lot of information to digest.

PS: are you writing books? if you aren't you should ;-)

**Comment by aeciopires** [comment]
kkkkk Thanks @BGmot!
I take your comment as a compliment and feel honored. But now I just want to plant a tree :-)

**[OFF-TOPPIC]**

 I've written 6 books in pt-BR, papers and dissertation, 12 years in the Zabbix-BR community and I still have a blog:

- 📖 [Descomplicando Kubernetes](https://livro.descomplicandokubernetes.com.br/pt/) (2020)
- 📖 [Integração Contínua com Jenkins](https://novatec.com.br/livros/jenkins) (2019)
- 📖 [Gerência de Configuração com Puppet](https://novatec.com.br/livros/puppet) (2017)
- 📖 [Apostila sobre Puppet](https://puppet-br.github.io/apostila-puppet) (2016)
- 📖 [De A a Zabbix](https://novatec.com.br/livros/zabbix) (2015)
- 📖 [Plataforma de Intercâmbio de Conteúdos Digitais](https://pt.scribd.com/doc/123206365/Plataforma-de-Intercambio-de-Conteudos-Digitais) (2014)

Papers and dissertation in pt-BR and en-US:

- [Pipeconf](https://gitlab.com/aeciopires/pipeconf) (2022)

Blog in pt-BR: http://aeciopires.com

I am a teacher in courses about Docker and Kubernetes in pt-BR:

* https://blog.aeciopires.com/curso-docker/
* https://blog.aeciopires.com/curso-kubernetes-k8s/

**Reply by BGmot** [reply]
I am speechless -) You've achieved a lot!

**Comment by ViperousTiger** [comment]
@aeciopires Hello,

Bare with me! I am currently facing an issue with a Zabbix deployment on an on-premises Kubernetes cluster configured with kubeadm. We have set up Zabbix with its components running within the cluster, and the Zabbix server service is temporarily exposed through a NodePort (port 31051) for testing purposes, though we plan to migrate to ingress-nginx soon.

The primary issue involves the Zabbix agent's communication: it attempts to connect to the Zabbix server on the default ports 10050 or 10051. However, due to our cluster configuration, these ports are not directly exposed, leading to unsuccessful connections as indicated in the agent's logs, which show attempts to connect to the node’s IP at port 10051.

Furthermore, there are discrepancies in the IP addresses logged by the Zabbix agent versus the IPs specified for the Zabbix server, suggesting possible network configuration or service discovery issues.

Could you guide me on how to correctly configure the Zabbix agent's settings to point to the new NodePort and any insights on addressing the IP address mismatches within our Kubernetes environment?

**Reply by aeciopires** [reply]
Hello @ViperousTiger!

Sorry for delay in answer.

I verified the helm chart and found many problems in services of the Zabbix components and launched the 4.4.1 version with fixes.

See:

- https://github.com/zabbix-community/helm-zabbix/releases/tag/zabbix-4.4.1
- https://github.com/zabbix-community/helm-zabbix/pull/95

Using this version I got exposed Zabbix Server, Proxy and Web using service of type LoadBalancer.

My specific values:

```yaml
[...]
zabbixServer:
  enabled: true
[...]
  service:
    type: LoadBalancer
    port: 10051
    nodePort: 31051
[...]

zabbixProxy:
  enabled: true
[...]
  service:
    type: LoadBalancer
    port: 10051
    nodePort: 31053
[...]


zabbixWeb:
  enabled: true
[...]
  service:
    type: LoadBalancer
    port: 80
[...]
```

I created a Zabbix Agent container  outside cluster and configured to connect using Zabbix Server loadbalancer IP in port default port (10051/TCP).

```bash
docker run -d --name zabbix-agent \
 --hostname "$(hostname)" \
 --privileged \
 -v /:/rootfs \
 -v /var/run:/var/run \
 --restart always \
 -p 10050:10050 \
 -e ZBX_HOSTNAME="$(hostname)" \
 -e ZBX_SERVER_HOST="LOADBALANCER_ADDRESS_ZABBIX_PROXY_OR_SERVER" \
 zabbix/zabbix-agent:6.4.15
```

I hope this help you.
