### DISCUSSION TITLE
Fine-Tuning Server settings

### DISCUSSION THREAD

**Discussion by Kovi117** [zabbix-community/helm-zabbix#45] [Q&A] [answered]
Hello everyone, I installed the chart and everything went OK, however, I would like to know how to fine-tune the server processes (i.e. number of pollers, cache size, etc) or in which part of the values.yaml file can I find these settings. Thank you very much!

Great job with this chart BTW!

**Comment by Kovi117** [comment]
Solved! I was putting those env variables in the wrong section, my bad.

**Reply by adriaaneyermede** [reply]
Hi KevAligo, We are facing the same problem. Can you please tell me in which section did you make the change please.

**Reply by Kovi117** [reply, marked as answer]
Sure, in the `values.yaml` file, add the required env variables when setting the Zabbix Server, something like this:
```
...
zabbixServer:
  enabled: true
  replicaCount: 1
  podAntiAffinity: true
  hostPort: false
  hostIP: 0.0.0.0
  image:
    repository: zabbix/zabbix-server-pgsql
    tag: null
    pullPolicy: IfNotPresent
  haNodesAutoClean:
    enabled: true
    image:
      repository: postgres
      tag: 15
      pullPolicy: IfNotPresent
    schedule: "0 1 * * *"
    deleteOlderThanSeconds: 3600
  service:
    type: LoadBalancer
    externalIPs: [192.168.1.1]
    port: 10051
    nodePort: 31051
  extraEnv:
    - name: ZBX_CACHESIZE
      value: 100M
    - name: ZBX_CACHEUPDATEFREQUENCY
      value: 60
    - name: ZBX_STARTDBSYNCERS
      value: 20
    - name: ZBX_STARTDISCOVERERS
      value: 10
    - name: ZBX_STARTPOLLERS
    - value: 60
...
```

You would have to adjust those variables to meet your requirements. You can find the entire list of variables in the corresponding docker hub site for each component. Hope it helps!
