### DISCUSSION TITLE
Changing values in zabbix_server.conf

### DISCUSSION THREAD

**Discussion by nowplayingtv** [zabbix-community/helm-zabbix#83] [General]
I'd like to enable VMware collectors which requires adjusting settings in zabbix_server.conf.

I don't see reference to these settings in the helm chart and wondering how to proceed.

StartVMwareCollectors=3
VMwareFrequency=60
VMwarePerfFrequency=60
VMwareCacheSize=32M
VMwareTimeout=120

**Comment by ViperousTiger** [comment]
@nowplayingtv You can actually add that stuff via env variables! Theres no documentation on the zabbix website for it but if you go to docker hub for zabbix server they will list the extra env variables! https://hub.docker.com/r/zabbix/zabbix-server-pgsql meaning you can do something like 

  extraEnv: 
   - name : ZBX_STARTVMWARECOLLECTORS
     value: 3

Let me know if you have any other questions! Hope this helps out!

**Reply by aeciopires** [reply]
Hello @nowplayingtv!

This question was answered by @ViperousTiger (thanks)
It is related to this issue: https://github.com/zabbix-community/helm-zabbix/issues/48 (contains an example of using extraEnv in this helm chart)

My example:

```
zabbixServer:
  enabled: true
#
#.... (hid other parameters)
# 
  extraEnv: 
    - name: "ZBX_STARTVMWARECOLLECTORS"
      value: "3"
    - name: "ZBX_VMWAREFREQUENCY"
      value: "60"
    - name: "ZBX_VMWAREPERFFREQUENCY"
      value: "60"
    - name: "ZBX_VMWARECACHESIZE"
      value: "32M"
    - name: "ZBX_VMWARETIMEOUT"
      value: "120"
```
