### DISCUSSION TITLE
How to change time zone?

### DISCUSSION THREAD

**Discussion by mscrocdile** [zabbix-community/helm-zabbix#97] [General]
How can one change time zone? What should one insert into values.yaml?
Reason is that in trigger expression time() one has to use UTC which is not comfortable.

**Comment by aeciopires** [comment]
Hello @mscrocdile!

You can use the ``TZ`` environment variable. See this link:  https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container

And you can pass this variable in the section ``zabbixServer.extraEnv`` (for example). See more details in this topic: https://github.com/zabbix-community/helm-zabbix/discussions/83

Example:

```yaml
zabbixServer:
  enabled: true
#
#.... (hid other parameters)
# 
  extraEnv: 
    - name: TZ
      value: "America/Sao_Paulo"
```
