### ISSUE TITLE
[zabbix-community/zabbix] extraVolumes and extraVolumeMounts for zabbix agent not working

### ISSUE THREAD

**Issue by GarbageYard** [zabbix-community/helm-zabbix#105]
**Describe the bug**
Even after enabling properties `extraVolumes` and `extraVolumeMounts` for zabbix agent in `values.yaml`, the created daemonset doesn't contain these properties.

**Version of Helm and Kubernetes**: 
Helm: v3.12.1
Kubernetes: v1.27.8

**What happened**:
The manifest does not contain `extraVolumes` and `extraVolumeMounts` 

**What you expected to happen**:
I want to mount a custom `zabbix_agent2.conf` file containing specific values for `Server` and `ServerActive` properties. For this I created a configmap and then used `extraVolumes` and `extraVolumeMounts` feature to mount the configmap. I expected to see my custom values in the file `zabbix_agent2.conf`. However, if I exec and check the agent pod, it has the following:
```
$ grep -Ev '#|^$' /etc/zabbix/zabbix_agent2.conf
LogType=console
Server=zabbix-server,0.0.0.0/0
ServerActive=zabbix-server:10051
Hostname=services-worker-4
EnablePersistentBuffer=0
Include=/etc/zabbix/zabbix_agentd.d/*.conf
ControlSocket=/tmp/agent.sock
Include=/etc/zabbix/zabbix_agent2.d/plugins.d/*.conf
```

**How to reproduce it** (as minimally and precisely as possible):
1) kubectl create configmap zabbix-agent-config --from-file=zabbix_agent2.conf=zabbix_agent2.conf -n monitoring
```
$ cat zabbix_agent2.conf
LogType=console
Server=zabbix-zabbix-helm-chrt-proxy,0.0.0.0/0
ServerActive=zabbix-zabbix-helm-chrt-proxy:10051
Hostname=services-worker-4
EnablePersistentBuffer=0
Include=/etc/zabbix/zabbix_agentd.d/*.conf
ControlSocket=/tmp/agent.sock
Include=/etc/zabbix/zabbix_agent2.d/plugins.d/*.conf
```

2) values.yaml
```
zabbixAgent:
  enabled: true
  runAsDaemonSet: true
  env:
  - name: ZBX_PASSIVESERVERS
    value: 0.0.0.0/0
  extraVolumes:
  - name: zabbix-agent-config
    configMap:
      name: zabbix-agent-config
  extraVolumeMounts:
  - name: zabbix-agent-config
    mountPath: /etc/zabbix
zabbixProxy:
  enabled: true
  env:
  - name: ZBX_HOSTNAME
    value: zabbix-proxy-stg
  - name: ZBX_SERVER_HOST
    value: zabbix.company.com:443
  - name: ZBX_CACHESIZE
    value: 256M
  - name: ZBX_VALUECACHESIZE
    value: 128M
  - name: ZBX_CONFIGFREQUENCY
    value: 60
```
**Anything else we need to know**:
Zabbix version: 6.0.28

**Comment by aeciopires** [comment]
Hello @GarbageYard!

Thanks for a issue so detailed. This help me a lot.

1) I fixed the bug of extraVolume for Zabbix Agent is this PR:  https://github.com/zabbix-community/helm-zabbix/pull/110
2) According the oficial documentation of Docker image of zabbix_agent2, you can't mount in ``/etc/zabbix`` directory. It is read only. You can mount in ``/etc/zabbix/zabbix_agentd.d``. Reference: https://hub.docker.com/r/zabbix/zabbix-agent2
3) According this discussion: https://stackoverflow.com/questions/33415913/whats-the-best-way-to-share-mount-one-file-into-a-pod, the syntax to mount only one file from configMap or Secret is a bit different.

Example:

```yaml
  extraVolumes:
  - name: zabbix-agent-config
    configMap:
      name: zabbix-agent-config
  extraVolumeMounts:
  - name: zabbix-agent-config
    mountPath: /etc/zabbix/zabbix_agent2.d/zabbix_agent2.conf
    subPath: zabbix_agent2.conf
```

4) The correct way to change values in ``/etc/zabbix/zabbix_agent2.conf`` file is using ``extraEnv`` for each config parameter supported in ``zabbix_agent2.conf`` file. 

Example:

```yaml
zabbixAgent:
  enabled: true
#
#.... (hid other parameters)
# 
  extraEnv: 
    - name: ZBX_TLSCERTFILE
      value: "xpto"
    - name: ZBX_HOSTNAMEITEM
      value: "xpto"
#.... (hid other parameters)
```

Using this approach, you don't need create the configmap.

References:
* https://github.com/zabbix-community/helm-zabbix/discussions/83
* https://hub.docker.com/r/zabbix/zabbix-agent2
