### ISSUE TITLE
[zabbix-community/zabbix] ha-labels-sidecar not created when zabbixAgent is run as DS

### ISSUE THREAD

**Issue by trc-ikeskin** [zabbix-community/helm-zabbix#136]
**Describe the bug**
When enabling the option to run the Zabbix agent as a DaemonSet instead of a sidecar, the `ha-labels-sidecar` is not added to the `zabbix-server` Deployment/Pods. This leads to the `zabbix-server` Service not able to select and point to the currently active Zabbix server pod due to the missing label on the Pod.

**Version of Helm and Kubernetes**:

- AWS EKS v1.30
- Helm v3.15.4+gfa9efb0 (via ArgoCD)

**What happened**:

The following line prevents the templating of the `ha-labels-sidecar` container in the `zabbix-server`deployment, when `.Values.zabbixAgent.runAsSidecar` is false (i.e. `.Values.zabbixAgent.runAsDaemonSet` is true):

https://github.com/zabbix-community/helm-zabbix/blob/47b3ed00ba0517afc946c553b9fd7c7f72a6a413/charts/zabbix/templates/deployment-zabbix-server.yaml#L201

**What you expected to happen**:

Remove the `.Values.zabbixAgent.runAsSidecar` condition.

**How to reproduce it** (as minimally and precisely as possible):

Deploy the helm chart using the following values:

```
  zabbixServer:
    enabled: true
    zabbixServerHA:
      enabled: true

  zabbixAgent:
    enabled: true
    runAsSidecar: false
    runAsDaemonSet: true
```

**Anything else we need to know**:

Is there something I am missing here as to why the sidecar should not be deployed when running the agent as a DaemonSet?
