### ISSUE TITLE
[zabbix-community/zabbix] wrong value of "StartJavaPollers" in config file

### ISSUE THREAD

**Issue by alex-vyverman** [zabbix-community/helm-zabbix#145]
**Describe the bug**
When `zabbixJavaGateway` is set to `enabled: false`, the env var `- name: ZBX_STARTJAVAPOLLERS` has no value, and creates an error `wrong value of "StartJavaPollers" in config file`

**Version of Helm and Kubernetes**:
helm v3.16.3
k3s v1.30.6+k3s1

**Anything else we need to know**:
`zabbixImageTag: ubuntu-7.2-latest` was set in zabbix-values.yaml

Adding for example 
```
- name: ZBX_STARTJAVAPOLLERS 
  value: "0"
```
 in the deployment works around the issue

**Comment by fibbs** [comment]
OK, I have to apologize! Actually, there is a bug in the Helm Chart causing to render the deployment manifest this way:

```
...
      - env:
      ...
        - name: ZBX_JAVAGATEWAYPORT
          value: "10052"
        - name: ZBX_STARTJAVAPOLLERS
        - name: ZBX_WEBDRIVERURL
          value: http://zabbix-chrome:4444
```

which causes the error reported by you. I am working on a bigger Pull Request right now and I will fix this issue there.
