### ISSUE TITLE
[zabbix-community/zabbix] secretSchemaKey not working as intended

### ISSUE THREAD

**Issue by Gazeka74** [zabbix-community/helm-zabbix#164]
**Describe the bug**
Fields secretSchemaKey and schema under postgresAccess do not work as intended

**Version of Helm and Kubernetes**:
latest in both cases

**What happened**:
Trying to deploy a fresh version of the chart with a new db doesn't work, Zabbix server get stuck on startup : 
```
** Preparing Zabbix server
** Preparing database
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: REDACTED
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: dev_zabbix
* DB_SERVER_SCHEMA: dev_zabbix
********************
** Database 'dev_zabbix' already exists. Please be careful with database owner!
** Creating 'dev_zabbix' schema in PostgreSQL
ERROR:  no schema has been selected to create in
LINE 1: CREATE TABLE role (
                     ^
```

**What you expected to happen**:
I'd expect it to work. To help compare, when removing the value in secretSchemaKey (to use the default public schema), I get this :

```
** Preparing Zabbix server
** Preparing database
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: REDACTED
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: dev_zabbix
* DB_SERVER_SCHEMA: public
********************
** Database 'dev_zabbix' already exists. Please be careful with database owner!
** Table 'dev_zabbix.dbversion' already exists.
Starting Zabbix Server. Zabbix 7.2.3 (revision ff99a1b).
Press Ctrl+C to exit.

     7:20250204:104948.653 Starting Zabbix Server. Zabbix 7.2.3 (revision ff99a1b).
     7:20250204:104948.653 ****** Enabled features ******
     7:20250204:104948.653 SNMP monitoring:           YES
     7:20250204:104948.653 IPMI monitoring:           YES
     7:20250204:104948.653 Web monitoring:            YES
     7:20250204:104948.653 VMware monitoring:         YES
     7:20250204:104948.653 SMTP authentication:       YES
     7:20250204:104948.653 ODBC:                      YES
     7:20250204:104948.653 SSH support:               YES

```

**How to reproduce it** (as minimally and precisely as possible):
Using an external PGSQL database, with a fresh database and no schema in it.
Regardless, when secretSchemaKey is set, it's unable to process the rest of the actions, as if the schema information wasn't properly passed to zabbix server

**Comment by Gazeka74** [comment]
I have a bit more information I can share.

i'm not sure if the zabbix-server is at fault here, I managed to catch the job create-upgrade-db ending trace :
```
(...)
ERROR:  current transaction is aborted, commands ignored until end of transaction block
job hook type is install
DB version found:  in database dev_zabbix and user dev_zabbix_usr on host REDACTED
db_version_major: , zbx_version_major: 7020
** initializing the major release upgrade process
Starting Zabbix Server. Zabbix 7.2.1 (revision 67f3c83).
Press Ctrl+C to exit.

    30:20250204:152435.717 Starting Zabbix Server. Zabbix 7.2.1 (revision 67f3c83).
    30:20250204:152435.717 ****** Enabled features ******
    30:20250204:152435.717 SNMP monitoring:           YES
    30:20250204:152435.717 IPMI monitoring:           YES
    30:20250204:152435.717 Web monitoring:            YES
    30:20250204:152435.717 VMware monitoring:         YES
    30:20250204:152435.754 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  relation "users" does not exist
LINE 1: select userid from users limit 1
                           ^
 [select userid from users limit 1]
    30:20250204:152435.754 cannot use database "dev_zabbix": database is not a Zabbix database 
```

So perhaps it is the job which fails to prepare the database properly to the zabbix server ?

**Comment by fibbs** [comment]
Thanks for your report @Gazeka74. Indeed, the last lines of the create-upgrade-db job look bad. First of all, the `ERROR` in the first line, then the fact that it wasn't able to recognize a DB schema version in the database (`DB version found: `) which seems to be a follow-up error of the one in the first line. Can you produce the full output of that job somehow?

Any chance to make this behavior reproducible for me? What kind of database are you using? Which version? How was it deployed?

Thanks

**Comment by Gazeka74** [comment]
I will try to get the output today, altough I'm not sure I'll be able to, since the job isn't kept in the history, whether it fails or not.

I'm using an Azure managed Postgresql version 14.12, but I guess the issue would be the same whatever base is underlying no ?

Also, the SQL i used, if that's any help :
```
-- create db + should swap query tool on it
CREATE DATABASE dev_zabbix WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';


-- Create environment role with password
CREATE ROLE user_zabbix_dev with CREATEDB inherit login password 'REDACTED';
ALTER ROLE user_zabbix_dev WITH password 'REDACTED';

-- Grant the role to the admin user
GRANT user_zabbix_dev TO primadmin;


-- Create Kong schema
CREATE SCHEMA dev_zabbix AUTHORIZATION user_zabbix_dev;

-- Set schema dedicated to environment as default schema for the role
ALTER ROLE user_zabbix_dev IN DATABASE dev_zabbix SET search_path TO dev_zabbix,public;

-- Grant the role privileges over all sequences in the environment schema
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dev_zabbix,public TO user_zabbix_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA dev_zabbix,public GRANT USAGE, SELECT ON SEQUENCES TO user_zabbix_dev;
```

**Comment by fibbs** [comment]
This is helpful for my own tests, thanks.

Did you create a secret containing all the `postgresAccess` relevant information then? Do you have `postgresAccess.secretSchemaKey` set in values.yaml?

Can you say more about your values.yaml? Maybe share it entirely?

I have done some tests yesterday and I believe I have found a glitch: when NOT using an existing secret but trying to supply the schema name directly via the values (`postgresAccess.schema`), the schema name is actually being used by the create-update-db job but ignored by the zabbix server pod later, causing the zabbix server pod to try to create the DB tables and stuff again, under "public".

I would nevertheless want to fully understand your issue before starting to further investigate and search a solution for this.

**Comment by Gazeka74** [comment]
Credentials to access the base were wrong... I was using the wrong user, which was allowed to write on the public schema but not on the dev_zabbix one...

Took me some time to figure this out but it worked directly on others environments, with the specified schema.
Fixed it on my first environment, and both the job and the server managed to connect to the database.

For your specific question, I did not use a dedicated secret, I was using the one generated by the chart. The postgresAccess looks like this ATM : 
```
postgresAccess:
  (...)
  existingSecretName: ""
  # -- key of the postgres access secret where host ip / dns name for the postgres db is found
  secretHostKey: host
  # -- key of the postgres access secret where the port for the postgres db is found
  secretPortKey: port
  # -- key of the postgres access secret where user name for the postgres db is found
  secretUserKey: user
  # -- key of the unified postgres access secret where password for the postgres db is found
  secretPasswordKey: password
  # -- key of the postgres access secret where database name for the postgres db is found
  secretDBKey: dbname
  # -- key of the postgres access secret where schema name for the postgres db is found. Can be left empty (defaults to "public", then). Only being used if external database is used (`postgresql.enabled` not set)
  secretSchemaKey: schema
  #
  # If you are not using an existing secret for all db relevant settings, you have to supply these here
  # a secret is then automatically generated containing those values under the above listed keys. This secret is then
  # being used in all components except the db-init-upgrade-job. The job will get the database access credentials
  # as literal values always if no existing secret is used, due to anatomy of Helm Charts and pre-install/pre-upgrade hooks
  # -- Address of database host - ignored if postgresql.enabled=true
  host: "REDACTED.postgres.database.azure.com"
  # -- Port of database host - ignored if postgresql.enabled=true or when existingSecretName is set
  port: "5432"
  # -- User of database, ignored if existingSecretName is set
  user: ref+azurekeyvault://kv-REDACTEDlogin
  # -- Password of database, eignored if existingSecretName is set
  password: ref+azurekeyvault://kv-REDACTEDpwd
  # -- Name of database, eignored if existingSecretName is set
  database: {{ requiredEnv "ENV" }}_zabbix
  # -- Schema of database. Can be left empty if secretSchemaKey is not set. Only being used if external database is used (`postgresql.enabled` not set)
  schema: {{ requiredEnv "ENV" }}_zabbix 
```

Sorry for the false positive !
