### ISSUE TITLE
Can't get zabbix-proxy recongnized via name - only IP

### ISSUE THREAD

**Issue by MaxDiOrio** [zabbix-community/helm-zabbix#179]
I've deployed zabbix proxy in the chart with default values - really I changed very little in the chart other than using an external postgress server and HA Zabbix server.  Installed in an EKS cluster

In the zabbix-proxy pod, I can see the container environment variable:
       ZBX_HOSTNAME:        zabbix-zabbix-proxy-0 (v1:metadata.name)  

On the server, I added the proxy and configured the proxy address as:  zabbix-proxy
I have also tried zabbix-zabbix-proxy-0
I have also tried the IP address, which does seem to work - although not a solution given the pod ip changes.

What am I doing wrong here? Thanks.


On the zabbix-proxy pod, I'm seeing:
```
zabbix-proxy     20:20250407:235417.455 In zbx_is_ip4() ip:'zabbix-zabbix-server'                                                                                                                                                                                        zabbix-proxy     20:20250407:235417.455 End of zbx_is_ip4():FAIL                                                                                                                                                                                                         zabbix-proxy     20:20250407:235417.455 In zbx_is_ip6() ip:'zabbix-zabbix-server'                                                                                                                                                                                        zabbix-proxy     20:20250407:235417.455 End of zbx_is_ip6():FAIL                                                                                                                                                                                                         zabbix-proxy     20:20250407:235417.455 End of zbx_connect_to_server():SUCCEED                                                                                                                                                                                           zabbix-proxy     20:20250407:235417.455 In zbx_put_data_to_server() datalen:122                                                                                                                                                                                          zabbix-proxy     20:20250407:235417.455 In zbx_recv_response()                                                                                                                                                                                                           
zabbix-proxy     20:20250407:235417.460 zbx_recv_response() '{"response":"failed","info":"connection is not allowed"}'
zabbix-proxy     20:20250407:235417.460 End of zbx_recv_response():FAIL                                                                                                                                                                                                  
zabbix-proxy     20:20250407:235417.460 End of zbx_put_data_to_server():FAIL                                                                                                                                                                                             
zabbix-proxy     20:20250407:235417.460 cannot send proxy data to server at "zabbix-zabbix-server": connection is not allowed
zabbix-proxy     20:20250407:235417.460 End of proxy_data_sender():FAIL more:0 flags:0x8000                                                 
```

On the zabbix-server, this is repeating:

```
zabbix-server    167:20250407:235125.812 cannot accept connection from proxy "zabbix-proxy" at "10.129.53.29", allowed address: "zabbix-proxy": connection is not allowed 
```

```
# Source: zabbix/templates/statefulset-zabbix-proxy.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-zabbix-proxy
  namespace: zabbix
  labels:
    helm.sh/chart: zabbix-7.0.6
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/version: "7.0.10"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: proxy
  annotations:
spec:
  replicas: 1
  serviceName: zabbix
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix
      app.kubernetes.io/instance: zabbix
      app.kubernetes.io/component: proxy
  template:
    metadata:
      annotations:
      labels:
        helm.sh/chart: zabbix-7.0.6
        app.kubernetes.io/name: zabbix
        app.kubernetes.io/instance: zabbix
        app.kubernetes.io/version: "7.0.10"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: proxy
    spec:
      serviceAccountName: zabbix
      containers:
        - name: zabbix-agent
          resources:
            {}
          securityContext:
            {}
          image: "zabbix/zabbix-agent2:ubuntu-7.2-latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZBX_SERVER_HOST
              value: "0.0.0.0/0"
            - name: ZBX_SERVER_PORT
              value: "10051"
            - name: ZBX_PASSIVE_ALLOW
              value: "true"
            - name: ZBX_PASSIVESERVERS
              value: 
            - name: ZBX_ACTIVE_ALLOW
              value: "true"
            - name: ZBX_ACTIVESERVERS
              value: 
            - name: ZBX_DEBUGLEVEL
              value: "3"
            - name: ZBX_TIMEOUT
              value: "4"
            - name: ZBX_LOADMODULE
              value: 
          ports:
            - name: zabbix-agent
              containerPort: 10050
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: zabbix-agent
            timeoutSeconds: 3
          startupProbe:
            failureThreshold: 5
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: zabbix-agent
            timeoutSeconds: 3
        - name: zabbix-proxy
          resources:
            {}
          securityContext:
            {}
          image: "zabbix/zabbix-proxy-sqlite3:ubuntu-7.2-latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: ZBX_PROXYMODE
              value: "0"
            - name: ZBX_HOSTNAME
              value: "zabbix-proxy"
            - name: ZBX_SERVER_HOST
              value: "zabbix-zabbix-server"
            - name: ZBX_SERVER_PORT
              value: "10051"
            - name: ZBX_LOADMODULE
              value: 
            - name: ZBX_DEBUGLEVEL
              value: "4"
            - name: ZBX_TIMEOUT
              value: "4"
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: "false"
            - name: ZBX_VMWARECACHESIZE
              value: "128M"
          ports:
            - name: zabbix-proxy
              containerPort: 10051
              protocol: TCP
      imagePullSecrets:
      volumes:
```
