### ISSUE TITLE
[zabbix-community/zabbix] issue title

### ISSUE THREAD

**Issue by Atoms** [zabbix-community/helm-zabbix#188]
in values.yaml 
global.commonLabels are ignored, and there are no labels added to any resources.

Additionally there is no possibility to add specific labels (e.g. for multicluster mesh needs) to service.

**Comment by aeciopires** [comment]
Hi @Atoms!

Thanks for reporting this. I will fix today in next PR.

This was implemented in the past, but we lost in some refactory: https://github.com/zabbix-community/helm-zabbix/pull/73/files#diff-f33962c0863493e91bcc10385622d8e3e6044b5e70efd6ea31218ca506bd6e3a

But you can use other values like this example (change componentName and objectName according the needs):

```yaml
componentName:
  extraDaemonSetLabels: {}
  extraStatefulsetLabels: {} 
  extraDeploymentLabels: {}
  extraPodLabels: {}
```

Example: 

```yaml
zabbixServer:
  extraDeploymentLabels:
    datacenter: "br"
```
