### ISSUE TITLE
[zabbix-community/zabbix] Adding extra params job-init-db-schema.yaml 

### ISSUE THREAD

**Issue by david-moreau** [zabbix-community/helm-zabbix#57]
Hi,

I opened an [issue](https://github.com/zabbix-community/helm-zabbix/issues/5) last year to add extras on cronjobs, I use a consul for my DB cluster and I need to manage DNS resolution in sidecare.

Is it possible to add extraContainers, extraVolumes, extraPodSpecs for "[job-init-db-schema.yaml](https://github.com/zabbix-community/helm-zabbix/blob/master/charts/zabbix/templates/configmap-zabbix-server-init-waitschema.yaml)"?

I'm not sure I fully understand the purpose of "job-init-db-schema.yaml", It's a fix for Zabbix-server version before 2.6.2 ?

David

**Comment by aeciopires** [comment]
Hello @david-moreau!

I create the follow values specif to jobDBSchema:

```yaml
zabbixServer:
  jobDBSchema:
    # -- additional init containers to start within the Zabbix Server Job DB Schema pod
    extraInitContainers: []
    # -- additional containers to start within the Zabbix Server Job DB Schema pod
    extraContainers: []
    # -- additional specifications to the Zabbix Server Job DB Schema pod
    extraPodSpecs: {}
    # -- additional volumeMounts to the Zabbix Server Job DB Schema pod
    extraVolumeMounts: []
    # -- additional volumes to make available to the  Zabbix Server Job DB Schema pod
    extraVolumes: []
    # -- Security Context configurations. Reference: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
    securityContext: {}
```
