### ISSUE TITLE
Where do I add `ZBX_CACHESIZE`?

### ISSUE THREAD

**Issue by bonzonkim** [zabbix-community/helm-zabbix#94]
using 4.3.0 version for helm chart, `zabbix/zabbix-server-pgsql` image for zabbixServer
`zabbix/zabbix-server-pgsql` image in the docker hub there is  `ZBX_CACHESIZE` in the env list but when I add `ZabbixServer.ZBX_CACHESIZE` doesn't work `ZabbixServer.ExtraEnv.ZBX_CACHESIZE` also doesn't work. 
only working way is edit deployment manually, I might missed something but I can't figure out

```
zabbixImageTag: ubuntu-6.0.20

postgresAccess:
  useUnifiedSecret: true
  unifiedSecretName: zabbixdb-pguser-zabbix
  host: "zabbix-postgresql"
  port: "5432"
  user: "zabbix"
  password: "password"
  database: "zabbix"
  unifiedSecretAutoCreate: true

zabbixServer:
  enabled: true
  replicaCount: 2
  namespace: test2
  image:
    repository: zabbix/zabbix-server-pgsql
  service:
    type: NodePort
    port: 10051
    nodePort: 31053

postgresql:
  enabled: true
  namespace: test2
  image:
    repository: postgres
    tag: 14
  max_connections: 100

  
zabbixAgent:
  enabled: true
  namespace: test2
  ZBX_HOSTNAME: zabbix-agent
  ZBX_SERVER_HOST: 0.0.0.0/0
  ZBX_SERVER_PORT: 10051
  ZBX_PASSIVE_ALLOW: true # This variable is boolean (true or false) and enables or disables feature of passive checks. By default, value is true
  ZBX_ACTIVE_ALLOW: false # This variable is boolean (true or false) and enables or disables feature of active checks
  ZBX_DEBUGLEVEL: 3 # The variable is used to specify debug level, from 0 to 5
  ZBX_TIMEOUT: 4 # The variable is used to specify timeout for processing checks. By default, value is 4.
  ZBX_VMWARECACHESIZE: 128M
  service:
    type: ClusterIP
    port: 10050

zabbixWeb:
  enabled: true
  namespace: test2
  ZBX_SERVER_HOST: zabbix-zabbix-server
  ZBX_SERVER_PORT: 10051
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 31082

ingress:
  enabled: true
  annotations: {}
  extraLabels: {}
  hosts:
    - host: zabbix.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  ingressClassName: nginx
  pathType: Prefix
```

above is the `values.yaml`file that I'm testing on the local where the `ZBX_CACHESIZE` should be listed?
