### ISSUE TITLE
[zabbix-community/zabbix] unstable connection to the zabbix-server service when in HA mode

### ISSUE THREAD

**Issue by szelga** [zabbix-community/helm-zabbix#98]
random (i.e., sometimes connection succeeds, sometimes fails) connection timeout to the port 10051 on the `zabbix-server` service.

**Version of Helm and Kubernetes**:

kubernetes version: v1.22.8

helm version: using ArgoCD 2.10 for zabbix deployment, so helm is v3. if the exact helm version is relevant for this issue, I will dig deeper.

**What happened**:

zabbix agents are unable to connect to the server for heartbeat message or active check most of the time:
```
2024/06/20 13:29:20.039885 [101] active check configuration update from host [zabbix-agent-host] started to fail
2024/06/20 13:30:13.989139 [101] cannot connect to [zabbix.company.name:10051]: dial tcp :0->13.13.13.13:10051: i/o timeout
2024/06/20 13:30:13.989185 [101] sending of heartbeat message for [zabbix-agent-host] started to fail
```
coincidentally, `telnet zabbix-zabbix-server.monitoring 10051` randomly succeeds or fails, so the problem is not in the ingress.

**What you expected to happen**:

connection should happen every time.

**How to reproduce it**:

I think, this could reliably be reproduced on any HA installation. below I will post the relevant `values.yaml` entries (because it might as well be misconfiguration on my part), feel free to request any additional details.

**Anything else we need to know**:

if I try to connect to individual zabbix-server pods via port 10051, only 1 (of 3) could be connected to (and it connects reliably). probably, the service is unaware, which pod is active at the moment and tries to connect randomly or something like that.

relevant values:

```yaml
zabbixServer:
  extraEnv:
    - name: ZBX_AUTOHANODENAME
      value: "fqdn"
  haNodesAutoClean:
    image:
      repository: timescale/timescaledb
      tag: latest-pg16
  replicaCount: 3
  service:
    type: ClusterIP
```

the other (relevant) values are unchanged.

when in not-HA mode, it works 100% of the time.
