### ISSUE TITLE
[zabbix-community/zabbix] issue title

### ISSUE THREAD

**Issue by 3mstecnologia** [zabbix-community/helm-zabbix#99]
**Describe the bug**
Impossible set CacheSize of Zabbix Server on 7.0.0

**Version of Helm and Kubernetes**:

Client Version: v1.28.11+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.11+k3s1

HELM version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}

**What happened**:

on workloads of zabbix his crash OUT OF MEMORY

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by aeciopires** [comment]
Hello @3mstecnologia!

You can configure CacheSize using environment variables! If you go to Docker Hub for the zabbix-server (https://hub.docker.com/r/zabbix/zabbix-server-pgsql) they will list the extra environment variables!  
Means you can do something like:

My example:

```yaml
zabbixServer:
  enabled: true
#
#.... (hid other parameters)
# 
  extraEnv: 
    - name: ZBX_CACHESIZE
      value: "8M"
    - name: ZBX_VALUECACHESIZE
      value: "8M"
```

Can you test?
